# Introduction

```{r, echo = FALSE, message = FALSE, warning=FALSE}
source(here::here("scripts/setup.R"))
```

We have chosen the theme of air pollution because global warming is a battle that will define our future as a species. Although more and more people from different backgrounds such as scientists, economists, or politicians are trying to prevent this crisis, no concrete amelioration has been registered so far. We believe that it is key to better understand the scope of air pollution’s impact on different metrics to realize the importance and emergency of the problem. We are especially interested in this, that this crisis affects multiple themes, such as health, nature, our economy, and its growth. However, for this project, we want to focus on the impact of air pollution on one of these, namely health. 

We chose to focus on health because we thought that it is something that affects everyone and that it will last for years to come, as we are producing more air pollution each year. We thought it would be interesting to compare the evolution of the mortality rate due to pollution with the evolution of air pollution to have a better picture of current trends and see how they are related to each other, and how fast they are growing.

While our research will focus on global issues, we wanted to understand how being from different parts of the world could affect air pollution. That is why we also decided to research the evolution of Air pollution during seasonal change. 

Overall, we decided to focus on a global scale because we come from 3 different countries located on 3 different continents. Indeed, we thought it would be great to have a grasp of the situation worldwide. That is why we picked multiple factors (e.g. economic factors, geographic location, seasons, pollutants, etc) to see how they affect health and air pollution.

### Related Work

The article written by Hannah Ritchie and Max Roser (2017) "Air Pollution" states that air pollution was responsible for 5 million deaths globally in 2017, meaning that it contributed 9% of deaths globally, it also mentions that air pollution is one of the leading risk factors of the disease burden affecting the quality of life lost. They also find a strong link between exposure to pollution (PM2.5) and total death rates from all pollution-related diseases. Thus, in our study, we would like to study further by focusing on the relationship between pollution and each pollution-related disease.

Another relevant article published by Xu-Qin Jiang, Xiao-Dong Mei, and Di Feng (2016) "Air pollution and chronic airway diseases: what should people know and do?" focus their approach on the concern of the effects of air pollution on human health by explaining the sources of the components from air pollutants, to determine the impact and the measures to be taken into account to reduce the effect of ambient air pollution.

### Research questions

#### 1. Descriptive Statistics

* 1.1   How have the air pollution levels changed from 1990 to 2019? How has the mortality rate changed?
* 1.2   What are the diseases with a higher correlation with air pollution?
* 1.3   Does air pollution change with the seasons?

#### 2. Inferential Statistics

* 2.1   What are the factors that impact air pollution the most(GDP and Agriculture)?
* 2.2   As a result of question 2.1, Are landlocked countries more polluted?
* 2.3   As a result of question 1.2, the variables “diseases” considered highly correlated with air pollution will be chosen for this question; What has been the effect of air pollution on some health diseases mortality?


